import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import PageTransition from "../components/PageTransition";
import StairTransition from "../components/StairTransition";
import { Toaster } from "react-hot-toast";
import Head from "next/head";


const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: '--font-jetbrainsMono'
});

export const metadata = {
  title: "Faisal Osman",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/logo.png" type="image/png" />
        <meta name="description" content="Your custom description" />
        <title>{metadata.title}</title>
      </Head>
      <body className={jetbrainsMono.variable}>
        <Header></Header>
        <StairTransition></StairTransition>
        <PageTransition>
          {children}
        </PageTransition>
        <Toaster
          position="top-center"
          reverseOrder={false}
        />
      </body>
    </html>
  );
}
